-- Metrics store, rollups and retention (F07, ADR-0003).
--
-- Raw samples are one row per check result with an array of values
-- (grouped layout); rollups are one row per series and bucket. Both are
-- partitioned by retention class (list), then by time (range), so retention
-- is DROP TABLE on whole partitions. The partition functions run as the
-- schema owner (SECURITY DEFINER): the system role can create and drop
-- partitions but cannot change anything else in the schema.
--
-- Samples and rollups carry no tenant_id. Tenant isolation is on
-- metric_groups and metric_series (RLS); the API resolves series through
-- them first and reads samples only by the group and series IDs it found.

-- +goose Up

-- Retention classes. Plugins name a class per metric; a tenant's
-- metric_classes limit decides which classes its checks may use.
CREATE TABLE retention_classes (
    id         smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       text        NOT NULL UNIQUE CHECK (name ~ '^[a-z0-9][a-z0-9-]{0,39}$'),
    created_at timestamptz NOT NULL DEFAULT now()
);
INSERT INTO retention_classes (id, name) VALUES (1, 'high-frequency'), (2, 'standard'), (3, 'capacity');
ALTER TABLE retention_classes ALTER COLUMN id RESTART WITH 4;

-- How long each level of a class is kept. No row: kept until a policy is
-- set. There are no built-in defaults (F07).
CREATE TABLE retention_policies (
    class_id   smallint    NOT NULL REFERENCES retention_classes (id) ON DELETE CASCADE,
    level      text        NOT NULL CHECK (level IN ('raw', '5m', '1h')),
    keep_days  integer     NOT NULL CHECK (keep_days BETWEEN 1 AND 36600),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (class_id, level)
);

-- One per (check, object, class, layout): the metrics of one result that
-- share a retention class. A changed plugin layout gets a new group, so old
-- rows are never reinterpreted.
CREATE TABLE metric_groups (
    id              bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    tenant_id       uuid        NOT NULL REFERENCES tenants (id) ON DELETE CASCADE,
    retention_class smallint    NOT NULL REFERENCES retention_classes (id),
    layout_version  integer     NOT NULL,
    device_id       uuid        NOT NULL,
    source_id       uuid        NOT NULL,              -- check (collectors later)
    plugin          text        NOT NULL,
    object_key      text        NOT NULL DEFAULT '',   -- '' or interface index, VM UUID, ...
    created_at      timestamptz NOT NULL DEFAULT now(),
    UNIQUE (source_id, object_key, retention_class, layout_version)
);
CREATE INDEX metric_groups_device ON metric_groups (tenant_id, device_id);

-- One per metric of a group. slot is the 1-based index into the group's
-- sample arrays.
CREATE TABLE metric_series (
    id        bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    tenant_id uuid     NOT NULL,
    group_id  bigint   NOT NULL REFERENCES metric_groups (id) ON DELETE CASCADE,
    slot      smallint NOT NULL CHECK (slot >= 1),
    name      text     NOT NULL,
    unit      text     NOT NULL DEFAULT '',
    kind      text     NOT NULL DEFAULT 'gauge' CHECK (kind IN ('gauge', 'rate')),
    labels    jsonb    NOT NULL DEFAULT '{}',
    UNIQUE (group_id, slot)
);
CREATE INDEX metric_series_name ON metric_series (tenant_id, name);

-- Raw samples. vals[slot] is NaN when the metric was not collected.
CREATE TABLE metric_samples (
    retention_class smallint    NOT NULL,
    group_id        bigint      NOT NULL,
    ts              timestamptz NOT NULL,
    vals            float8[]    NOT NULL
) PARTITION BY LIST (retention_class);
CREATE INDEX metric_samples_group_ts ON metric_samples (group_id, ts);

CREATE TABLE metric_rollup_5m (
    retention_class smallint    NOT NULL,
    series_id       bigint      NOT NULL,
    ts              timestamptz NOT NULL,   -- bucket start
    min             float8      NOT NULL,
    max             float8      NOT NULL,
    sum             float8      NOT NULL,
    count           integer     NOT NULL,
    PRIMARY KEY (retention_class, series_id, ts)
) PARTITION BY LIST (retention_class);

CREATE TABLE metric_rollup_1h (
    retention_class smallint    NOT NULL,
    series_id       bigint      NOT NULL,
    ts              timestamptz NOT NULL,
    min             float8      NOT NULL,
    max             float8      NOT NULL,
    sum             float8      NOT NULL,
    count           integer     NOT NULL,
    PRIMARY KEY (retention_class, series_id, ts)
) PARTITION BY LIST (retention_class);

-- Rollups are complete for buckets before done_until.
CREATE TABLE metric_rollup_watermarks (
    level           text        NOT NULL CHECK (level IN ('5m', '1h')),
    retention_class smallint    NOT NULL REFERENCES retention_classes (id) ON DELETE CASCADE,
    done_until      timestamptz NOT NULL,
    updated_at      timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (level, retention_class)
);

-- +goose StatementBegin
-- Partition period and name suffix per table: raw and 5-minute rollups by
-- day, hourly rollups by month.
CREATE FUNCTION metrics_partition_period(p_table text) RETURNS text
LANGUAGE sql IMMUTABLE SET search_path = pg_catalog
AS $$ SELECT CASE p_table WHEN 'metric_rollup_1h' THEN 'month' ELSE 'day' END $$;

-- Creates the class partitions and the time partitions covering
-- [p_from, p_until] for every retention class. Idempotent and safe to call
-- from several nodes. Returns the number of partitions created.
CREATE FUNCTION metrics_ensure_partitions(p_from timestamptz, p_until timestamptz) RETURNS integer
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public
AS $$
DECLARE
    c       record;
    tbl     text;
    period  text;
    parent  text;
    part    text;
    lo      timestamptz;
    hi      timestamptz;
    created integer := 0;
BEGIN
    IF p_until < p_from OR p_until - p_from > interval '400 days' THEN
        RAISE EXCEPTION 'partition range % to % is not allowed', p_from, p_until;
    END IF;
    PERFORM pg_advisory_xact_lock(hashtext('metrics_ensure_partitions'));
    FOR c IN SELECT id FROM retention_classes ORDER BY id LOOP
        FOREACH tbl IN ARRAY ARRAY['metric_samples', 'metric_rollup_5m', 'metric_rollup_1h'] LOOP
            period := metrics_partition_period(tbl);
            parent := format('%s_c%s', tbl, c.id);
            IF to_regclass('public.' || parent) IS NULL THEN
                EXECUTE format('CREATE TABLE public.%I PARTITION OF public.%I FOR VALUES IN (%s) PARTITION BY RANGE (ts)',
                               parent, tbl, c.id);
            END IF;
            lo := date_trunc(period, p_from, 'UTC');
            WHILE lo <= p_until LOOP
                hi := lo + ('1 ' || period)::interval;
                part := parent || '_' || to_char(lo AT TIME ZONE 'UTC',
                        CASE period WHEN 'day' THEN '"d"YYYYMMDD' ELSE '"m"YYYYMM' END);
                IF to_regclass('public.' || part) IS NULL THEN
                    EXECUTE format('CREATE TABLE public.%I PARTITION OF public.%I FOR VALUES FROM (%L) TO (%L)',
                                   part, parent, lo, hi);
                    created := created + 1;
                END IF;
                lo := hi;
            END LOOP;
        END LOOP;
    END LOOP;
    RETURN created;
END
$$;

-- Drops time partitions that end before now minus the retention of their
-- class and level. Returns the dropped partition names.
CREATE FUNCTION metrics_drop_expired() RETURNS SETOF text
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public
AS $$
DECLARE
    p      record;
    r      record;
    tbl    text;
    period text;
    parent regclass;
    hi     timestamptz;
BEGIN
    -- Dropping a partition locks its parent; never queue writers behind a
    -- long dashboard query. The next maintenance run retries.
    PERFORM set_config('lock_timeout', '5s', true);
    PERFORM pg_advisory_xact_lock(hashtext('metrics_ensure_partitions'));
    FOR p IN SELECT class_id, level, keep_days FROM retention_policies LOOP
        tbl := CASE p.level WHEN 'raw' THEN 'metric_samples' WHEN '5m' THEN 'metric_rollup_5m' ELSE 'metric_rollup_1h' END;
        period := metrics_partition_period(tbl);
        parent := to_regclass(format('public.%s_c%s', tbl, p.class_id));
        CONTINUE WHEN parent IS NULL;
        FOR r IN SELECT c.relname FROM pg_inherits i JOIN pg_class c ON c.oid = i.inhrelid
                  WHERE i.inhparent = parent ORDER BY c.relname LOOP
            -- Partition names carry their UTC start; hi is the end.
            hi := CASE period
                WHEN 'day' THEN (to_date(substring(r.relname FROM '_d(\d{8})$'), 'YYYYMMDD') + interval '1 day')
                ELSE (to_date(substring(r.relname FROM '_m(\d{6})$'), 'YYYYMM') + interval '1 month') END
                AT TIME ZONE 'UTC';
            IF hi IS NOT NULL AND hi <= now() - make_interval(days => p.keep_days) THEN
                EXECUTE format('DROP TABLE public.%I', r.relname);
                RETURN NEXT r.relname::text;
            END IF;
        END LOOP;
    END LOOP;
END
$$;
-- +goose StatementEnd

REVOKE ALL ON FUNCTION metrics_ensure_partitions(timestamptz, timestamptz), metrics_drop_expired() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION metrics_ensure_partitions(timestamptz, timestamptz), metrics_drop_expired() TO monitor_system;

SELECT metrics_ensure_partitions(now() - interval '1 day', now() + interval '3 days');

ALTER TABLE metric_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE metric_series ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON metric_groups
    USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);
CREATE POLICY tenant_isolation ON metric_series
    USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);

GRANT SELECT ON retention_classes, retention_policies, metric_groups, metric_series,
                metric_samples, metric_rollup_5m, metric_rollup_1h, metric_rollup_watermarks TO monitor_app;
-- Retention is platform-wide; only the platform key's handlers write it.
GRANT INSERT, UPDATE, DELETE ON retention_classes, retention_policies TO monitor_app;
GRANT SELECT ON metric_rollup_watermarks TO monitor_system;
-- `monitor admin retention` (standalone installs have no platform key).
GRANT SELECT, INSERT, UPDATE, DELETE ON retention_classes, retention_policies TO monitor_system;
GRANT SELECT, INSERT ON metric_groups, metric_series, metric_samples TO monitor_system;
GRANT SELECT, INSERT, UPDATE ON metric_rollup_5m, metric_rollup_1h TO monitor_system;
GRANT INSERT, UPDATE ON metric_rollup_watermarks TO monitor_system;

-- Views for Grafana (F07). Dashboards query these, never the base tables,
-- so the storage layout can change. They run with the owner's rights and
-- show every tenant: the monitor_grafana role is for the platform operator.
CREATE VIEW metric_series_v AS
SELECT s.id AS series_id, s.tenant_id, g.device_id, d.name AS device_name, g.source_id AS check_id,
       c.name AS check_name, g.plugin, g.object_key AS object, s.name, s.unit, s.kind, s.labels,
       rc.name AS retention_class
  FROM metric_series s
  JOIN metric_groups g ON g.id = s.group_id
  JOIN retention_classes rc ON rc.id = g.retention_class
  LEFT JOIN devices d ON d.id = g.device_id
  LEFT JOIN checks c ON c.id = g.source_id;

CREATE VIEW metrics_raw AS
SELECT m.ts AS time, s.id AS series_id, s.tenant_id, g.device_id, g.source_id AS check_id,
       g.object_key AS object, s.name, s.unit, m.vals[s.slot] AS value
  FROM metric_samples m
  JOIN metric_groups g ON g.id = m.group_id AND g.retention_class = m.retention_class
  JOIN metric_series s ON s.group_id = g.id
 WHERE m.vals[s.slot] <> 'NaN'::float8;

CREATE VIEW metrics_5m AS
SELECT r.ts AS time, s.id AS series_id, s.tenant_id, g.device_id, g.source_id AS check_id,
       g.object_key AS object, s.name, s.unit, r.min, r.max, r.sum / r.count AS avg, r.sum, r.count
  FROM metric_rollup_5m r
  JOIN metric_series s ON s.id = r.series_id
  JOIN metric_groups g ON g.id = s.group_id;

CREATE VIEW metrics_1h AS
SELECT r.ts AS time, s.id AS series_id, s.tenant_id, g.device_id, g.source_id AS check_id,
       g.object_key AS object, s.name, s.unit, r.min, r.max, r.sum / r.count AS avg, r.sum, r.count
  FROM metric_rollup_1h r
  JOIN metric_series s ON s.id = r.series_id
  JOIN metric_groups g ON g.id = s.group_id;

CREATE VIEW devices_v AS
SELECT d.id, d.tenant_id, t.name AS tenant_name, d.name, d.type, d.address, d.site_id, st.name AS site_name,
       d.parent_id, d.tags,
       CASE
           WHEN hc.id IS NULL THEN 'unmonitored'
           WHEN NOT hc.enabled THEN 'disabled'
           WHEN hs.check_id IS NULL OR hs.status = 'UNKNOWN' THEN 'unknown'
           WHEN hs.phase = 'PROBLEM' THEN 'down'
           ELSE 'up' END AS availability,
       (SELECT count(*) FROM incidents i WHERE i.device_id = d.id AND i.status <> 'resolved') AS open_incidents
  FROM devices d
  JOIN tenants t ON t.id = d.tenant_id
  LEFT JOIN sites st ON st.id = d.site_id
  LEFT JOIN checks hc ON hc.device_id = d.id AND hc.is_host_check
  LEFT JOIN check_state hs ON hs.check_id = hc.id;

CREATE VIEW check_states_v AS
SELECT c.id AS check_id, c.tenant_id, c.device_id, d.name AS device_name, c.name, c.plugin, c.enabled,
       c.interval_seconds, s.phase, s.status, s.since, s.last_result_at, s.last_status, s.last_output, s.incident_id
  FROM checks c
  JOIN devices d ON d.id = c.device_id
  LEFT JOIN check_state s ON s.check_id = c.id;

CREATE VIEW incidents_v AS
SELECT i.id, i.tenant_id, i.device_id, d.name AS device_name, i.check_id, c.name AS check_name, i.severity,
       i.status, i.summary, i.flapping, i.opened_at, i.acknowledged_at, i.resolved_at, i.resolved_by,
       coalesce(i.resolved_at, now()) - i.opened_at AS duration
  FROM incidents i
  LEFT JOIN devices d ON d.id = i.device_id
  LEFT JOIN checks c ON c.id = i.check_id;

-- The Grafana role is optional: deploy/postgres/init-roles.sql creates it.
-- +goose StatementBegin
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'monitor_grafana') THEN
        GRANT SELECT ON metric_series_v, metrics_raw, metrics_5m, metrics_1h, devices_v, check_states_v,
                        incidents_v TO monitor_grafana;
    END IF;
END
$$;
-- +goose StatementEnd

-- +goose Down
DROP VIEW incidents_v, check_states_v, devices_v, metrics_1h, metrics_5m, metrics_raw, metric_series_v;
DROP FUNCTION metrics_drop_expired();
DROP FUNCTION metrics_ensure_partitions(timestamptz, timestamptz);
DROP FUNCTION metrics_partition_period(text);
DROP TABLE metric_rollup_watermarks, metric_rollup_1h, metric_rollup_5m, metric_samples, metric_series,
           metric_groups, retention_policies, retention_classes;
